### ISSUE TITLE
Problem with ES6 arrow function

### ISSUE THREAD

**Issue by azhabinsky** [homerjam/angular-images-loaded#14]
While building our AngularJS app we use gulp-uglify. 
Unfortunately there is an error when gulp-uglify tries to minify this line as it can't minify code in ES6-notation. 

https://github.com/homerjam/angular-images-loaded/blob/977b9e2339e7d3f743eebc67c259bdf9762327b8/angular-images-loaded.js#L23

**Comment by homerjam** [comment]
Ah yes, that shouldn't be there 😊
