### ISSUE TITLE
RequireJS path doesn't load the imagesLoaded factory

### ISSUE THREAD

**Issue by itonics-tbeauvais** [homerjam/angular-images-loaded#5]
We are using Require JS to lazily load modules into application.  This works like a beauty but it seems that your module uses imagesloaded.js which uses Require as well and simply returns the factory.

Something needs to happen here.  We had to manually assign the factory globally (because your module doesn't use Require) so that your module can see it.  

Either update your documentation to include Require (which I can provide a few ideas/snippets) or bounce the idea of on require of imageloaded.js then it is loaded in to the window.
 
applicaiton.js
define(['...', '...', 'imagesLoaded'], function (..., ..., imagesLoaded) {
    window.imagesLoaded = imagesLoaded;
}

Any ideas?

**Comment by homerjam** [comment]
Hi,

I've not got much experience using RequireJS and angular together - could you show me a (simplified) example to help me understand - with your main.js, app.js files perhaps? I'd also like to see any snippets/ideas you have.

I've added `imagesLoaded` as a constant within the module, might this solve the issue?

**Comment by itonics-tbeauvais** [comment]
Hrm, it's hard to give an example.. here is the basic strategy that we use: http://weblogs.asp.net/dwahlin/dynamically-loading-controllers-and-views-with-angularjs-and-requirejs

Now, that doesn't have much to do with the problem.  The problem is really the accessibility of the factory.  Take a look at imagesload.js @ 18.

`return factory( window, EventEmitter, eventie );`

It doesn't assign it anywhere globally.  It just goes away into the ether.  

I think your adding it to the directive declaration might work but I'd have to pull to make sure.

Thanks for the insight and quick feedback.

**Comment by homerjam** [comment]
Ok, let me know if that does work.

If you can submit a PR that covers what you need I'll gladly take a look. I'm afraid that right now I'm unsure what needs to happen.
