### ISSUE TITLE
Loading statement

### ISSUE THREAD

**Issue by Tamxaun** [homerjam/angular-images-loaded#6]
How do I make a "loading" effect of image, that is shown in imagesloaded.

**Comment by homerjam** [comment]
Could you show me a reference please?

**Comment by Tamxaun** [comment]
like here http://imagesloaded.desandro.com/ (black images after clicked "add images")

**Comment by homerjam** [comment]
Did you take a look at the example - it shows a simple use case with loading effect?

**Comment by Tamxaun** [comment]
I didn't figure out how it fits to "angular-images-loaded"

**Comment by homerjam** [comment]
I think perhaps you'll need to take a look at the angular docs to get a better general understanding of directives. Once you have that I think you'll be able to figure it out - this is rather simple as directives go.

I'm closing this for now.
