### ISSUE TITLE
Please Add to NPM

### ISSUE THREAD

**Issue by lelandcope** [homerjam/angular-images-loaded#7]
Please add your directive to npm this way it can easily be used with things like browserify.

**Comment by homerjam** [comment]
Here ya go: [https://www.npmjs.com/package/angular-images-loaded](https://www.npmjs.com/package/angular-images-loaded)

I don't really know if this will work with Browserify out of the box, I don't use it :blush:. Would appreciate any help/testing you can do.

**Comment by lelandcope** [comment]
Yah let me know when you update the repo so i can take a look at your package.json.

**Comment by homerjam** [comment]
Just did :+1:

**Comment by lelandcope** [comment]
I would do an `npm i angular imagesloaded --save` that way it will include the dependencies needed for your lib.

Great work BTW and thanks for the directive.

**Comment by homerjam** [comment]
Sweet, thanks.

I'm gonna close this - let me know if anything else is needed for Browserify to work.
