### ISSUE TITLE
Issue with ng data binding

### ISSUE THREAD

**Issue by mikeabeln** [homerjam/angular-images-loaded#9]
Example:
`<img class="ng-cloak" ng-cloak ng-src="{{currentState().src}}" images-loaded="imgLoadedEvents">`

When I call a function that updates the {{currentState().src}} data to request a new image, none of the events fire. Is this an issue or is there a proposed solution I'm overlooking?

Thanks!

**Comment by homerjam** [comment]
I hadn't really considered this use case but perhaps we could watch the `src`/`ng-src` attribute and reapply the listeners.

**Comment by homerjam** [comment]
Actually this is already a feature of the directive! Please add `images-loaded-watch="currentState().src"` to the element. I've updated the example/readme to show this too.

**Comment by mikeabeln** [comment]
Perfect! Thanks for the help and!

**Comment by mikeabeln** [comment]
The module itself!
